### ISSUE TITLE
Why RethinkDB? 

### ISSUE THREAD

**Issue by talp101** [clique-service/clique-final-project#1]
What are the benefits for using Rethink in this scenario?

Seems like RDBMS will be a great fit here :dart:

**Comment by Schniz** [comment]
Hey there.

You are correct. RDBMS _is_ a great fit here, **considering the hardware we got**.
The app was running on 2 node cluster of 8GB RAM and 8 cores at our college servers with 100% usage.
After the project showcase, I downloaded all the data (5GB of data) and migrated it into PostgreSQL with couple of tables. I wrote a query that returns the same data we used to get from RethinkDB and it took 50 seconds to complete. It was very fast, comparing to the query on RethinkDB which was about 20 minutes.

However, the whole point of the application is to leverage "big data" concepts, and when I say "big data" I mean "distribute the data, distribute the processing". The application was (first) built to scale its processing to thousands of servers, of lets say, Raspberry Pis. PostgreSQL and MariaDB, from my knowledge, wouldn't be the best fit in this case. I don't know if the current state of the project will support thousands of servers and won't make it to saturation pretty fast, but that was only to make it work faster using the 2 "monolithic" servers we had at our college.

Sorry for the late reply, dude 😄
